# Generated by Django 3.1.4 on 2021-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210113_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
